//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Depressurizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Depressurizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying Data.
        /// </summary>
        internal static string Applying_Data {
            get {
                return ResourceManager.GetString("Applying_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Category_All {
            get {
                return ResourceManager.GetString("Category_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        internal static string Category_Favorite {
            get {
                return ResourceManager.GetString("Category_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        internal static string Category_Games {
            get {
                return ResourceManager.GetString("Category_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string Category_Hidden {
            get {
                return ResourceManager.GetString("Category_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        internal static string Category_Software {
            get {
                return ResourceManager.GetString("Category_Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncategorized.
        /// </summary>
        internal static string Category_Uncategorized {
            get {
                return ResourceManager.GetString("Category_Uncategorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VR.
        /// </summary>
        internal static string Category_VR {
            get {
                return ResourceManager.GetString("Category_VR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scraping.
        /// </summary>
        internal static string Scraping {
            get {
                return ResourceManager.GetString("Scraping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scraping Apps: {0} / {1} Completed.
        /// </summary>
        internal static string Scraping_Status {
            get {
                return ResourceManager.GetString("Scraping_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time left.
        /// </summary>
        internal static string Time_Left {
            get {
                return ResourceManager.GetString("Time_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
