language: csharp
solution: src/Depressurizer.sln
install:
  - nuget restore src/Depressurizer.sln
  - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/Depressurizer.Core/Depressurizer.Core.csproj
  - xbuild /p:Configuration=Release src/Depressurizer.Tests/Depressurizer.Tests.csproj
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./src/Depressurizer.Tests/bin/Release/Depressurizer.Tests.dll
