language: csharp
solution: src/Depressurizer.sln

git:
  depth: 10

# Use latest images for building: https://blog.travis-ci.com/2017-12-01-new-update-schedule-for-linux-build-images
group: travis_latest

dotnet: 2.2
mono: none

env:
  global:
    - CONFIGURATION: Release
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - NET_CORE_VERSION: netcoreapp2.2

script:
  - dotnet build ./src/Depressurizer.Tests/Depressurizer.Tests.csproj -c "$CONFIGURATION" -f "$NET_CORE_VERSION"
  - dotnet test ./src/Depressurizer.Tests/Depressurizer.Tests.csproj -c "$CONFIGURATION" -f "$NET_CORE_VERSION"
