language: csharp
dist: trusty
mono: none
dotnet: 1.0.1
solution: src/Depressurizer.sln
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test ./src/Depressurizer.Tests/Depressurizer.Tests.csproj
