language: csharp
solution: src/Depressurizer.sln

os:
  - linux
  - osx

matrix:
  include:
    - dotnet: 2.1.502
      mono: none
    - mono: latest

script:
  - dotnet build ./src/Depressurizer.Tests/Depressurizer.Tests.csproj
  - dotnet test ./src/Depressurizer.Tests/Depressurizer.Tests.csproj
