language: csharp
solution: src/Depressurizer.sln

dotnet: 2.1.502
mono: none

script:
  - dotnet build ./src/Depressurizer.Tests/Depressurizer.Tests.csproj
  - dotnet test ./src/Depressurizer.Tests/Depressurizer.Tests.csproj --verbosity detailed
