//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Depressurizer.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Depressurizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}\userdata\{1}\7\remote\sharedconfig.vdf.
        /// </summary>
        internal static string ConfigFilePath {
            get {
                return ResourceManager.GetString("ConfigFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}\userdata\{1}\760\screenshots.vdf.
        /// </summary>
        internal static string ScreenshotsFilePath {
            get {
                return ResourceManager.GetString("ScreenshotsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}\userdata\{1}\config\shortcuts.vdf.
        /// </summary>
        internal static string ShortCutsFilePath {
            get {
                return ResourceManager.GetString("ShortCutsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://steamcommunity.com/id/{0}/games?tab=all.
        /// </summary>
        internal static string UrlCustomGameListHtml {
            get {
                return ResourceManager.GetString("UrlCustomGameListHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://steamcommunity.com/id/{0}/games?tab=all&amp;xml=1.
        /// </summary>
        internal static string UrlCustomGameListXml {
            get {
                return ResourceManager.GetString("UrlCustomGameListXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://steamcommunity.com/id/{0}?xml=1.
        /// </summary>
        internal static string UrlCustomProfileXml {
            get {
                return ResourceManager.GetString("UrlCustomProfileXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://steamcommunity.com/profiles/{0}/games?tab=all.
        /// </summary>
        internal static string UrlGameListHtml {
            get {
                return ResourceManager.GetString("UrlGameListHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://steamcommunity.com/profiles/{0}/games?tab=all&amp;xml=1.
        /// </summary>
        internal static string UrlGameListXml {
            get {
                return ResourceManager.GetString("UrlGameListXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://store.steampowered.com/app/{0}/.
        /// </summary>
        internal static string UrlSteamStore {
            get {
                return ResourceManager.GetString("UrlSteamStore", resourceCulture);
            }
        }
    }
}
