//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18052
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Depressurizer {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Depressurizer.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finishing up....
        /// </summary>
        internal static string CDlgDataScrape_FinishingUp {
            get {
                return ResourceManager.GetString("CDlgDataScrape_FinishingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Initiating Steam Store data scrape. {0} jobs to complete..
        /// </summary>
        internal static string CDlgDataScrape_InitiatingSteamStoreDataScrape {
            get {
                return ResourceManager.GetString("CDlgDataScrape_InitiatingSteamStoreDataScrape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scrape completed. {0} failures. {1} results. Merging results into game data..
        /// </summary>
        internal static string CDlgDataScrape_ScrapeCompleted {
            get {
                return ResourceManager.GetString("CDlgDataScrape_ScrapeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 
        ///Time Remaining:.
        /// </summary>
        internal static string CDlgDataScrape_TimeRemaining {
            get {
                return ResourceManager.GetString("CDlgDataScrape_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updating...{0}/{1} complete..
        /// </summary>
        internal static string CDlgDataScrape_UpdatingComplete {
            get {
                return ResourceManager.GetString("CDlgDataScrape_UpdatingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloading game list....
        /// </summary>
        internal static string CDlgFetch_DownloadingGameList {
            get {
                return ResourceManager.GetString("CDlgFetch_DownloadingGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finishing download....
        /// </summary>
        internal static string CDlgFetch_FinishingDownload {
            get {
                return ResourceManager.GetString("CDlgFetch_FinishingDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updating Game List.
        /// </summary>
        internal static string CDlgFetch_UpdatingGameList {
            get {
                return ResourceManager.GetString("CDlgFetch_UpdatingGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attempting to download XML profile page for custom URL name {0}: {1}.
        /// </summary>
        internal static string CDlgGetSteamID_AttemptingDownloadXMLProfile {
            get {
                return ResourceManager.GetString("CDlgGetSteamID_AttemptingDownloadXMLProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exception when downloading XML profile:\n{0}.
        /// </summary>
        internal static string CDlgGetSteamID_ExceptionDownloadingXMLProfile {
            get {
                return ResourceManager.GetString("CDlgGetSteamID_ExceptionDownloadingXMLProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to download profile data:.
        /// </summary>
        internal static string CDlgGetSteamID_FailedToDownloadProfile {
            get {
                return ResourceManager.GetString("CDlgGetSteamID_FailedToDownloadProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting Steam ID from Custom URL....
        /// </summary>
        internal static string CDlgGetSteamID_GettingIDFromURL {
            get {
                return ResourceManager.GetString("CDlgGetSteamID_GettingIDFromURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Getting Steam ID....
        /// </summary>
        internal static string CDlgGetSteamID_GettingSteamID {
            get {
                return ResourceManager.GetString("CDlgGetSteamID_GettingSteamID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successfully downloaded XML profile..
        /// </summary>
        internal static string CDlgGetSteamID_XMLProfileDownloaded {
            get {
                return ResourceManager.GetString("CDlgGetSteamID_XMLProfileDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt; 1 minute.
        /// </summary>
        internal static string CDlgScrape_1minute {
            get {
                return ResourceManager.GetString("CDlgScrape_1minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Applying data....
        /// </summary>
        internal static string CDlgScrape_ApplyingData {
            get {
                return ResourceManager.GetString("CDlgScrape_ApplyingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scraping game info.
        /// </summary>
        internal static string CDlgScrape_ScrapingGameInfo {
            get {
                return ResourceManager.GetString("CDlgScrape_ScrapingGameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown.
        /// </summary>
        internal static string CDlgScrape_Unknown {
            get {
                return ResourceManager.GetString("CDlgScrape_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updating game list....
        /// </summary>
        internal static string CDlgUpdateProfile_UpdatingGameList {
            get {
                return ResourceManager.GetString("CDlgUpdateProfile_UpdatingGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aborted. Updated {0} / {1} entries..
        /// </summary>
        internal static string DBEditDlg_AbortedUpdate {
            get {
                return ResourceManager.GetString("DBEditDlg_AbortedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Added game with ID {0}..
        /// </summary>
        internal static string DBEditDlg_AddedGame {
            get {
                return ResourceManager.GetString("DBEditDlg_AddedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete {0} games from the database?.
        /// </summary>
        internal static string DBEditDlg_AreYouSureDeleteGames {
            get {
                return ResourceManager.GetString("DBEditDlg_AreYouSureDeleteGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to clear all data?.
        /// </summary>
        internal static string DBEditDlg_AreYouSureToClear {
            get {
                return ResourceManager.GetString("DBEditDlg_AreYouSureToClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canceled list update..
        /// </summary>
        internal static string DBEditDlg_CanceledListUpdate {
            get {
                return ResourceManager.GetString("DBEditDlg_CanceledListUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cleared all data..
        /// </summary>
        internal static string DBEditDlg_ClearedAllData {
            get {
                return ResourceManager.GetString("DBEditDlg_ClearedAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        internal static string DBEditDlg_Confirm {
            get {
                return ResourceManager.GetString("DBEditDlg_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database saved..
        /// </summary>
        internal static string DBEditDlg_DatabaseSaved {
            get {
                return ResourceManager.GetString("DBEditDlg_DatabaseSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database save failed..
        /// </summary>
        internal static string DBEditDlg_DatabaseSaveFailed {
            get {
                return ResourceManager.GetString("DBEditDlg_DatabaseSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleted {0} games..
        /// </summary>
        internal static string DBEditDlg_DeletedGames {
            get {
                return ResourceManager.GetString("DBEditDlg_DeletedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GZip Files (*.gz)|*.gz|XML Files (*.xml)|*.xml|All Files|*.*.
        /// </summary>
        internal static string DBEditDlg_DialogFilter {
            get {
                return ResourceManager.GetString("DBEditDlg_DialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edited game with ID {0}.
        /// </summary>
        internal static string DBEditDlg_EditedGame {
            get {
                return ResourceManager.GetString("DBEditDlg_EditedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string DBEditDlg_Error {
            get {
                return ResourceManager.GetString("DBEditDlg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error saving file: 
        ///
        ///{0}.
        /// </summary>
        internal static string DBEditDlg_ErrorSavingFile {
            get {
                return ResourceManager.GetString("DBEditDlg_ErrorSavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error updating game list..
        /// </summary>
        internal static string DBEditDlg_ErrorUpdatingGameList {
            get {
                return ResourceManager.GetString("DBEditDlg_ErrorUpdatingGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error updating games..
        /// </summary>
        internal static string DBEditDlg_ErrorUpdatingGames {
            get {
                return ResourceManager.GetString("DBEditDlg_ErrorUpdatingGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while updating the game list:
        ///
        ///{0}.
        /// </summary>
        internal static string DBEditDlg_ErrorWhileUpdatingGameList {
            get {
                return ResourceManager.GetString("DBEditDlg_ErrorWhileUpdatingGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while updating games:
        ///
        ///{0}.
        /// </summary>
        internal static string DBEditDlg_ErrorWhileUpdatingGames {
            get {
                return ResourceManager.GetString("DBEditDlg_ErrorWhileUpdatingGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to add game with ID {0}..
        /// </summary>
        internal static string DBEditDlg_FailedToAddGame {
            get {
                return ResourceManager.GetString("DBEditDlg_FailedToAddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File loaded..
        /// </summary>
        internal static string DBEditDlg_FileLoaded {
            get {
                return ResourceManager.GetString("DBEditDlg_FileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File saved..
        /// </summary>
        internal static string DBEditDlg_FileSaved {
            get {
                return ResourceManager.GetString("DBEditDlg_FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game with specified ID already exists..
        /// </summary>
        internal static string DBEditDlg_GameIdAlreadyExists {
            get {
                return ResourceManager.GetString("DBEditDlg_GameIdAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No games to scrape..
        /// </summary>
        internal static string DBEditDlg_NoGamesToScrape {
            get {
                return ResourceManager.GetString("DBEditDlg_NoGamesToScrape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save failed..
        /// </summary>
        internal static string DBEditDlg_SaveFailed {
            get {
                return ResourceManager.GetString("DBEditDlg_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} selected / {1} displayed / {2} total.
        /// </summary>
        internal static string DBEditDlg_SelectedDisplayedTotal {
            get {
                return ResourceManager.GetString("DBEditDlg_SelectedDisplayedTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unsaved changes.
        /// </summary>
        internal static string DBEditDlg_UnsavedChanges {
            get {
                return ResourceManager.GetString("DBEditDlg_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are unsaved changes. Save to the game database first?.
        /// </summary>
        internal static string DBEditDlg_UnsavedChangesSave {
            get {
                return ResourceManager.GetString("DBEditDlg_UnsavedChangesSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update canceled..
        /// </summary>
        internal static string DBEditDlg_UpdateCanceled {
            get {
                return ResourceManager.GetString("DBEditDlg_UpdateCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updated {0} entries..
        /// </summary>
        internal static string DBEditDlg_UpdatedEntries {
            get {
                return ResourceManager.GetString("DBEditDlg_UpdatedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updated game list, added {0} games..
        /// </summary>
        internal static string DBEditDlg_UpdatedGameList {
            get {
                return ResourceManager.GetString("DBEditDlg_UpdatedGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        internal static string DBEditDlg_Warning {
            get {
                return ResourceManager.GetString("DBEditDlg_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clipboard updated..
        /// </summary>
        internal static string DlgFatalError_ClipboardUpdated {
            get {
                return ResourceManager.GetString("DlgFatalError_ClipboardUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not copy to clipboard..
        /// </summary>
        internal static string DlgFatalError_CouldNotCopyClipboard {
            get {
                return ResourceManager.GetString("DlgFatalError_CouldNotCopyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not save error information..
        /// </summary>
        internal static string DlgFatalError_CouldNotSaveErrorInformation {
            get {
                return ResourceManager.GetString("DlgFatalError_CouldNotSaveErrorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error information saved..
        /// </summary>
        internal static string DlgFatalError_ErrorInformationSaved {
            get {
                return ResourceManager.GetString("DlgFatalError_ErrorInformationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} - Fatal Error.
        /// </summary>
        internal static string DlgFatalError_FatalError {
            get {
                return ResourceManager.GetString("DlgFatalError_FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A fatal error has occurred in {0}. The program will now terminate..
        /// </summary>
        internal static string DlgFatalError_FatalErrorOcurred {
            get {
                return ResourceManager.GetString("DlgFatalError_FatalErrorOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Game.
        /// </summary>
        internal static string DlgGame_CreateGame {
            get {
                return ResourceManager.GetString("DlgGame_CreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Game.
        /// </summary>
        internal static string DlgGame_EditGame {
            get {
                return ResourceManager.GetString("DlgGame_EditGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        internal static string DlgGameDBEntry_Add {
            get {
                return ResourceManager.GetString("DlgGameDBEntry_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game ID must be an integer..
        /// </summary>
        internal static string DlgGameDBEntry_IDMustBeInteger {
            get {
                return ResourceManager.GetString("DlgGameDBEntry_IDMustBeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If ID is selected, entry must be a number..
        /// </summary>
        internal static string DlgManualDownload_IfIDSelectedMustBeNumber {
            get {
                return ResourceManager.GetString("DlgManualDownload_IfIDSelectedMustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error saving settings file:.
        /// </summary>
        internal static string DlgOptions_ErrorSavingSettingsFile {
            get {
                return ResourceManager.GetString("DlgOptions_ErrorSavingSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account ID must be a number..
        /// </summary>
        internal static string DlgProfile_AccountIDMustBeNumber {
            get {
                return ResourceManager.GetString("DlgProfile_AccountIDMustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelling....
        /// </summary>
        internal static string DlgProfile_Cancelling {
            get {
                return ResourceManager.GetString("DlgProfile_Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click Update to get display names for the account numbers above..
        /// </summary>
        internal static string DlgProfile_ClickUpdateToDisplayNames {
            get {
                return ResourceManager.GetString("DlgProfile_ClickUpdateToDisplayNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not find the Steam profile specified..
        /// </summary>
        internal static string DlgProfile_CouldNotFindSteamProfile {
            get {
                return ResourceManager.GetString("DlgProfile_CouldNotFindSteamProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exception raised when trying to scrape profile name for account {0}:.
        /// </summary>
        internal static string DlgProfile_ExceptionRaisedWhenTryingScrapeProfileName {
            get {
                return ResourceManager.GetString("DlgProfile_ExceptionRaisedWhenTryingScrapeProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to create parent directory of profile file..
        /// </summary>
        internal static string DlgProfile_FailedToCreateParentDirectory {
            get {
                return ResourceManager.GetString("DlgProfile_FailedToCreateParentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profiles (*.profile)|*.profile.
        /// </summary>
        internal static string DlgProfile_Filter {
            get {
                return ResourceManager.GetString("DlgProfile_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No account configuration information was found in your Steam installation folder. You must enter your 64-bit account ID OR your Custom URL name manually..
        /// </summary>
        internal static string DlgProfile_NoAccountConfiguration {
            get {
                return ResourceManager.GetString("DlgProfile_NoAccountConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updating names....
        /// </summary>
        internal static string DlgProfile_UpdatingNames {
            get {
                return ResourceManager.GetString("DlgProfile_UpdatingNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a valid profile file path..
        /// </summary>
        internal static string DlgProfile_YouMustEnterValidProfilePath {
            get {
                return ResourceManager.GetString("DlgProfile_YouMustEnterValidProfilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a That path does not exist. Are you sure?.
        /// </summary>
        internal static string DlgSteamPath_ThatPathDoesNotExist {
            get {
                return ResourceManager.GetString("DlgSteamPath_ThatPathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access denied on Steam config file:.
        /// </summary>
        internal static string GameData_AccessDeniedSteamConfigFile {
            get {
                return ResourceManager.GetString("GameData_AccessDeniedSteamConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Added new game found in Steam config: {0} - {1}.
        /// </summary>
        internal static string GameData_AddedNewGame {
            get {
                return ResourceManager.GetString("GameData_AddedNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adding game {0} to config file..
        /// </summary>
        internal static string GameData_AddingGameToConfigFile {
            get {
                return ResourceManager.GetString("GameData_AddingGameToConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attempting to download HTML game list from URL {0}.
        /// </summary>
        internal static string GameData_AttemptingDownloadHTMLGameList {
            get {
                return ResourceManager.GetString("GameData_AttemptingDownloadHTMLGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attempting to download XML game list from URL {0}.
        /// </summary>
        internal static string GameData_AttemptingDownloadXMLGameList {
            get {
                return ResourceManager.GetString("GameData_AttemptingDownloadXMLGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cleaning up steam config tree before writing to disk..
        /// </summary>
        internal static string GameData_CleaningUpSteamConfigTree {
            get {
                return ResourceManager.GetString("GameData_CleaningUpSteamConfigTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error opening Steam config file: {0}.
        /// </summary>
        internal static string GameData_ErrorOpeningConfigFileParam {
            get {
                return ResourceManager.GetString("GameData_ErrorOpeningConfigFileParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error opening Steam config file:.
        /// </summary>
        internal static string GameData_ErrorOpeningSteamConfigFile {
            get {
                return ResourceManager.GetString("GameData_ErrorOpeningSteamConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error parsing Steam config file: {0}.
        /// </summary>
        internal static string GameData_ErrorParsingConfigFileParam {
            get {
                return ResourceManager.GetString("GameData_ErrorParsingConfigFileParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error parsing Steam config file:.
        /// </summary>
        internal static string GameData_ErrorParsingSteamConfigFile {
            get {
                return ResourceManager.GetString("GameData_ErrorParsingSteamConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error saving steam config file: {0}.
        /// </summary>
        internal static string GameData_ErrorSavingSteamConfigFile {
            get {
                return ResourceManager.GetString("GameData_ErrorSavingSteamConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exception when downloading HTML game list:
        ///{0}.
        /// </summary>
        internal static string GameData_ExceptionDownloadHTMLGameList {
            get {
                return ResourceManager.GetString("GameData_ExceptionDownloadHTMLGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exception when downloading XML game list:
        ///{0}.
        /// </summary>
        internal static string GameData_ExceptionDownloadXMLGameList {
            get {
                return ResourceManager.GetString("GameData_ExceptionDownloadXMLGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to save Steam config file: Invalid path specified..
        /// </summary>
        internal static string GameData_FailedToSaveSteamConfigBadPath {
            get {
                return ResourceManager.GetString("GameData_FailedToSaveSteamConfigBadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to save Steam config file:.
        /// </summary>
        internal static string GameData_FailedToSaveSteamConfigFile {
            get {
                return ResourceManager.GetString("GameData_FailedToSaveSteamConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integrated game into game list: {0} - {1}. New: {2}.
        /// </summary>
        internal static string GameData_IntegratedGameIntoGameList {
            get {
                return ResourceManager.GetString("GameData_IntegratedGameIntoGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integrated HTML data into game list. {0} total items, {1} new..
        /// </summary>
        internal static string GameData_IntegratedHTMLDataIntoGameList {
            get {
                return ResourceManager.GetString("GameData_IntegratedHTMLDataIntoGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integrated XML data into game list. {0} total items, {1} new..
        /// </summary>
        internal static string GameData_IntegratedXMLDataIntoGameList {
            get {
                return ResourceManager.GetString("GameData_IntegratedXMLDataIntoGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading existing Steam config failed: {0}.
        /// </summary>
        internal static string GameData_LoadingErrorSteamConfig {
            get {
                return ResourceManager.GetString("GameData_LoadingErrorSteamConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opening Steam config file: {0}.
        /// </summary>
        internal static string GameData_OpeningSteamConfigFile {
            get {
                return ResourceManager.GetString("GameData_OpeningSteamConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Processed game from Steam config: {0}, Cat: {1}, Fav: {2}.
        /// </summary>
        internal static string GameData_ProcessedGame {
            get {
                return ResourceManager.GetString("GameData_ProcessedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile is not public..
        /// </summary>
        internal static string GameData_ProfileNotPublic {
            get {
                return ResourceManager.GetString("GameData_ProfileNotPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removing game {0} category info from Steam config file..
        /// </summary>
        internal static string GameData_RemovingGameCategoryFromSteamConfig {
            get {
                return ResourceManager.GetString("GameData_RemovingGameCategoryFromSteamConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saving Steam config file: {0}..
        /// </summary>
        internal static string GameData_SavingSteamConfigFile {
            get {
                return ResourceManager.GetString("GameData_SavingSteamConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Skipped integrating game: {0} - {1}..
        /// </summary>
        internal static string GameData_SkippedIntegratingGame {
            get {
                return ResourceManager.GetString("GameData_SkippedIntegratingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Skipped processing game {0} from Steam config..
        /// </summary>
        internal static string GameData_SkippedProcessingGame {
            get {
                return ResourceManager.GetString("GameData_SkippedProcessingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The specified profile is not public..
        /// </summary>
        internal static string GameData_SpecifiedProfileNotPublic {
            get {
                return ResourceManager.GetString("GameData_SpecifiedProfileNotPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Steam config file loaded. {0} items found..
        /// </summary>
        internal static string GameData_SteamConfigFileLoaded {
            get {
                return ResourceManager.GetString("GameData_SteamConfigFileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successfully downloaded HTML game list..
        /// </summary>
        internal static string GameData_SuccessDownloadHTMLGameList {
            get {
                return ResourceManager.GetString("GameData_SuccessDownloadHTMLGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Successfully downloaded XML game list..
        /// </summary>
        internal static string GameData_SuccessDownloadXMLGameList {
            get {
                return ResourceManager.GetString("GameData_SuccessDownloadXMLGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Writing to disk....
        /// </summary>
        internal static string GameData_WritingToDisk {
            get {
                return ResourceManager.GetString("GameData_WritingToDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloading Steam app list..
        /// </summary>
        internal static string GameDB_DownloadingSteamAppList {
            get {
                return ResourceManager.GetString("GameDB_DownloadingSteamAppList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GameDB saved..
        /// </summary>
        internal static string GameDB_GameDBSaved {
            get {
                return ResourceManager.GetString("GameDB_GameDBSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GameDB XML document parsed..
        /// </summary>
        internal static string GameDB_GameDBXMLParsed {
            get {
                return ResourceManager.GetString("GameDB_GameDBXMLParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GameDB XML processed, load complete..
        /// </summary>
        internal static string GameDB_GameDBXMLProcessed {
            get {
                return ResourceManager.GetString("GameDB_GameDBXMLProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Initiating store scrape for game id {0}.
        /// </summary>
        internal static string GameDB_InitiatingStoreScrapeForGame {
            get {
                return ResourceManager.GetString("GameDB_InitiatingStoreScrapeForGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loaded {0} new items from the app list..
        /// </summary>
        internal static string GameDB_LoadedNewItemsFromAppList {
            get {
                return ResourceManager.GetString("GameDB_LoadedNewItemsFromAppList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading GameDB from {0}.
        /// </summary>
        internal static string GameDB_LoadingGameDBFrom {
            get {
                return ResourceManager.GetString("GameDB_LoadingGameDBFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saving GameDB to {0}.
        /// </summary>
        internal static string GameDB_SavingGameDBTo {
            get {
                return ResourceManager.GetString("GameDB_SavingGameDBTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scraping {0}: Age check with no redirect, or too many redirects (on #{1}).
        /// </summary>
        internal static string GameDB_ScrapingAgeCheckNoRedirect {
            get {
                return ResourceManager.GetString("GameDB_ScrapingAgeCheckNoRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scraping {0}: Could not parse info from page.
        /// </summary>
        internal static string GameDB_ScrapingCouldNotParse {
            get {
                return ResourceManager.GetString("GameDB_ScrapingCouldNotParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scraping {0}: Hit age check for id {1}.
        /// </summary>
        internal static string GameDB_ScrapingHitAgeCheck {
            get {
                return ResourceManager.GetString("GameDB_ScrapingHitAgeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scraping {0}: Page read.
        /// </summary>
        internal static string GameDB_ScrapingPageRead {
            get {
                return ResourceManager.GetString("GameDB_ScrapingPageRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scraping {0}: Page read failed. {1}.
        /// </summary>
        internal static string GameDB_ScrapingPageReadFailed {
            get {
                return ResourceManager.GetString("GameDB_ScrapingPageReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scraping {0}: Parsed. Genre: {1}. Redirect: {2}.
        /// </summary>
        internal static string GameDB_ScrapingParsed {
            get {
                return ResourceManager.GetString("GameDB_ScrapingParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scraping {0}: Parsed. DLC. Genre: {1}.
        /// </summary>
        internal static string GameDB_ScrapingParsedDLC {
            get {
                return ResourceManager.GetString("GameDB_ScrapingParsedDLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scraping {0}: Received Site Error.
        /// </summary>
        internal static string GameDB_ScrapingReceivedSiteError {
            get {
                return ResourceManager.GetString("GameDB_ScrapingReceivedSiteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scraping {0}: Redirecting to {1}.
        /// </summary>
        internal static string GameDB_ScrapingRedirectedTo {
            get {
                return ResourceManager.GetString("GameDB_ScrapingRedirectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scraping {0}: Redirected to main store page.
        /// </summary>
        internal static string GameDB_ScrapingRedirectedToMainStorePage {
            get {
                return ResourceManager.GetString("GameDB_ScrapingRedirectedToMainStorePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scraping {0}: Redirected to a non-app URL.
        /// </summary>
        internal static string GameDB_ScrapingRedirectedToNonApp {
            get {
                return ResourceManager.GetString("GameDB_ScrapingRedirectedToNonApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scraping {0}: Redirected to another app id ({1}).
        /// </summary>
        internal static string GameDB_ScrapingRedirectedToOtherApp {
            get {
                return ResourceManager.GetString("GameDB_ScrapingRedirectedToOtherApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scraping {0}: Stuck at age gate, redirect with no number (URL: {1}).
        /// </summary>
        internal static string GameDB_ScrapingStuckAtAgeCheck {
            get {
                return ResourceManager.GetString("GameDB_ScrapingStuckAtAgeCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XML App list downloaded..
        /// </summary>
        internal static string GameDB_XMLAppListDownloaded {
            get {
                return ResourceManager.GetString("GameDB_XMLAppListDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This action will add the contents of a Steam community game list to the currently loaded game list. If you do not want to do this, close the open game list or profile first.
        ///Continue loading games?.
        /// </summary>
        internal static string MainForm_AddContentsOfSteamCommunity {
            get {
                return ResourceManager.GetString("MainForm_AddContentsOfSteamCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This action will add the contents of a Steam config file to the currently loaded game list, and will overwrite the category information for any existing games. If you do not want to do this, close the open profile or gamelist first.
        ///Continue loading file?.
        /// </summary>
        internal static string MainForm_AddContentsOfSteamConfigFile {
            get {
                return ResourceManager.GetString("MainForm_AddContentsOfSteamConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Added game..
        /// </summary>
        internal static string MainForm_AddedGame {
            get {
                return ResourceManager.GetString("MainForm_AddedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;All&gt;.
        /// </summary>
        internal static string MainForm_All {
            get {
                return ResourceManager.GetString("MainForm_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autoname canceled..
        /// </summary>
        internal static string MainForm_AutonameCanceled {
            get {
                return ResourceManager.GetString("MainForm_AutonameCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autonamed {0} games..
        /// </summary>
        internal static string MainForm_AutonamedGames {
            get {
                return ResourceManager.GetString("MainForm_AutonamedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canceled web update..
        /// </summary>
        internal static string MainForm_CanceledWebUpdate {
            get {
                return ResourceManager.GetString("MainForm_CanceledWebUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category &apos;{0}&apos; added..
        /// </summary>
        internal static string MainForm_CategoryAdded {
            get {
                return ResourceManager.GetString("MainForm_CategoryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category &apos;{0}&apos; deleted..
        /// </summary>
        internal static string MainForm_CategoryDeleted {
            get {
                return ResourceManager.GetString("MainForm_CategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category name &apos;{0}&apos; is reserved..
        /// </summary>
        internal static string MainForm_CategoryNameReserved {
            get {
                return ResourceManager.GetString("MainForm_CategoryNameReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category names cannot be empty..
        /// </summary>
        internal static string MainForm_CategoryNamesNotEmpty {
            get {
                return ResourceManager.GetString("MainForm_CategoryNamesNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category renamed..
        /// </summary>
        internal static string MainForm_CategoryRenamed {
            get {
                return ResourceManager.GetString("MainForm_CategoryRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cleared data..
        /// </summary>
        internal static string MainForm_ClearedData {
            get {
                return ResourceManager.GetString("MainForm_ClearedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not add category &apos;{0}&apos;.
        /// </summary>
        internal static string MainForm_CouldNotAddCategory {
            get {
                return ResourceManager.GetString("MainForm_CouldNotAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not delete category &apos;{0}&apos;..
        /// </summary>
        internal static string MainForm_CouldNotDeleteCategory {
            get {
                return ResourceManager.GetString("MainForm_CouldNotDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        internal static string MainForm_Create {
            get {
                return ResourceManager.GetString("MainForm_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create category.
        /// </summary>
        internal static string MainForm_CreateCategory {
            get {
                return ResourceManager.GetString("MainForm_CreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data exported..
        /// </summary>
        internal static string MainForm_DataExported {
            get {
                return ResourceManager.GetString("MainForm_DataExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete category &apos;{0}&apos;?.
        /// </summary>
        internal static string MainForm_DeleteCategory {
            get {
                return ResourceManager.GetString("MainForm_DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download aborted..
        /// </summary>
        internal static string MainForm_DownloadAborted {
            get {
                return ResourceManager.GetString("MainForm_DownloadAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Downloaded {0} games, {1} new, via {2}..
        /// </summary>
        internal static string MainForm_DownloadedGames {
            get {
                return ResourceManager.GetString("MainForm_DownloadedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download failed..
        /// </summary>
        internal static string MainForm_DownloadFailed {
            get {
                return ResourceManager.GetString("MainForm_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edited game..
        /// </summary>
        internal static string MainForm_EditedGame {
            get {
                return ResourceManager.GetString("MainForm_EditedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter new category name:.
        /// </summary>
        internal static string MainForm_EnterNewCategoryName {
            get {
                return ResourceManager.GetString("MainForm_EnterNewCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter new name:.
        /// </summary>
        internal static string MainForm_EnterNewName {
            get {
                return ResourceManager.GetString("MainForm_EnterNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error downloading the profile data: 
        ///{0}.
        /// </summary>
        internal static string MainForm_ErrorDowloadingProfile {
            get {
                return ResourceManager.GetString("MainForm_ErrorDowloadingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error downloading game list.
        /// </summary>
        internal static string MainForm_ErrorDownloadingGameList {
            get {
                return ResourceManager.GetString("MainForm_ErrorDownloadingGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error downloading games..
        /// </summary>
        internal static string MainForm_ErrorDownloadingGames {
            get {
                return ResourceManager.GetString("MainForm_ErrorDownloadingGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error downloading profile data via {0}..
        /// </summary>
        internal static string MainForm_ErrorDownloadingProfileData {
            get {
                return ResourceManager.GetString("MainForm_ErrorDownloadingProfileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error exporting to Steam.
        /// </summary>
        internal static string MainForm_ErrorExportingToSteam {
            get {
                return ResourceManager.GetString("MainForm_ErrorExportingToSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error importing steam data list.
        /// </summary>
        internal static string MainForm_ErrorImportingSteamDataList {
            get {
                return ResourceManager.GetString("MainForm_ErrorImportingSteamDataList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error loading game database. Local category and DLC data will not be available.
        ///
        ///.
        /// </summary>
        internal static string MainForm_ErrorLoadingGameDB {
            get {
                return ResourceManager.GetString("MainForm_ErrorLoadingGameDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error loading profile.
        /// </summary>
        internal static string MainForm_ErrorLoadingProfile {
            get {
                return ResourceManager.GetString("MainForm_ErrorLoadingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errors occurred on {0} games..
        /// </summary>
        internal static string MainForm_ErrorOcurredOnGames {
            get {
                return ResourceManager.GetString("MainForm_ErrorOcurredOnGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error saving file..
        /// </summary>
        internal static string MainForm_ErrorSavingFile {
            get {
                return ResourceManager.GetString("MainForm_ErrorSavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error saving profile.
        /// </summary>
        internal static string MainForm_ErrorSavingProfile {
            get {
                return ResourceManager.GetString("MainForm_ErrorSavingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exported categories..
        /// </summary>
        internal static string MainForm_ExportedCategories {
            get {
                return ResourceManager.GetString("MainForm_ExportedCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export failed..
        /// </summary>
        internal static string MainForm_ExportFailed {
            get {
                return ResourceManager.GetString("MainForm_ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to load profile..
        /// </summary>
        internal static string MainForm_FailedLoadProfile {
            get {
                return ResourceManager.GetString("MainForm_FailedLoadProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to save profile..
        /// </summary>
        internal static string MainForm_FailedSaveProfile {
            get {
                return ResourceManager.GetString("MainForm_FailedSaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to load store pages for {0} games..
        /// </summary>
        internal static string MainForm_FailedToLoadStorePages {
            get {
                return ResourceManager.GetString("MainForm_FailedToLoadStorePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;Favorite&gt;.
        /// </summary>
        internal static string MainForm_Favorite {
            get {
                return ResourceManager.GetString("MainForm_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GameDB file does not exist..
        /// </summary>
        internal static string MainForm_GameDBFileNotExist {
            get {
                return ResourceManager.GetString("MainForm_GameDBFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} games not found in the local database. Check the Steam Store for these game genres?.
        /// </summary>
        internal static string MainForm_GamesNotFoundInGameDB {
            get {
                return ResourceManager.GetString("MainForm_GamesNotFoundInGameDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ignored {0} game{1}..
        /// </summary>
        internal static string MainForm_IgnoredGame {
            get {
                return ResourceManager.GetString("MainForm_IgnoredGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imported {0} games..
        /// </summary>
        internal static string MainForm_ImportedGames {
            get {
                return ResourceManager.GetString("MainForm_ImportedGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imported {0} items..
        /// </summary>
        internal static string MainForm_ImportedItems {
            get {
                return ResourceManager.GetString("MainForm_ImportedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import failed..
        /// </summary>
        internal static string MainForm_ImportFailed {
            get {
                return ResourceManager.GetString("MainForm_ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name &apos;{0}&apos; is already in use..
        /// </summary>
        internal static string MainForm_NameIsInUse {
            get {
                return ResourceManager.GetString("MainForm_NameIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No game data found. Please make sure the custom URL name is spelled correctly..
        /// </summary>
        internal static string MainForm_NoGameDataFound {
            get {
                return ResourceManager.GetString("MainForm_NoGameDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning: No game info found in the specified file..
        /// </summary>
        internal static string MainForm_NoGameInfoFound {
            get {
                return ResourceManager.GetString("MainForm_NoGameInfoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No games found..
        /// </summary>
        internal static string MainForm_NoGamesFound {
            get {
                return ResourceManager.GetString("MainForm_NoGamesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No games in download..
        /// </summary>
        internal static string MainForm_NoGamesInDownload {
            get {
                return ResourceManager.GetString("MainForm_NoGamesInDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No profile loaded. Create one now?.
        /// </summary>
        internal static string MainForm_NoProfileLoaded {
            get {
                return ResourceManager.GetString("MainForm_NoProfileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overwrite?.
        /// </summary>
        internal static string MainForm_Overwrite {
            get {
                return ResourceManager.GetString("MainForm_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to overwrite existing names? Saying \&quot;No\&quot; will only rename games that do not have a name set..
        /// </summary>
        internal static string MainForm_OverwriteExistingNames {
            get {
                return ResourceManager.GetString("MainForm_OverwriteExistingNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile created..
        /// </summary>
        internal static string MainForm_ProfileCreated {
            get {
                return ResourceManager.GetString("MainForm_ProfileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile edited..
        /// </summary>
        internal static string MainForm_ProfileEdited {
            get {
                return ResourceManager.GetString("MainForm_ProfileEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile loaded..
        /// </summary>
        internal static string MainForm_ProfileLoaded {
            get {
                return ResourceManager.GetString("MainForm_ProfileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile saved..
        /// </summary>
        internal static string MainForm_ProfileSaved {
            get {
                return ResourceManager.GetString("MainForm_ProfileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removed {0} empty categories..
        /// </summary>
        internal static string MainForm_RemovedEmptyCategories {
            get {
                return ResourceManager.GetString("MainForm_RemovedEmptyCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removed {0} game{1}..
        /// </summary>
        internal static string MainForm_RemovedGame {
            get {
                return ResourceManager.GetString("MainForm_RemovedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove {0} game{1}?.
        /// </summary>
        internal static string MainForm_RemoveGame {
            get {
                return ResourceManager.GetString("MainForm_RemoveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rename.
        /// </summary>
        internal static string MainForm_Rename {
            get {
                return ResourceManager.GetString("MainForm_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rename category: {0}.
        /// </summary>
        internal static string MainForm_RenameCategory {
            get {
                return ResourceManager.GetString("MainForm_RenameCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saving profile data failed:.
        /// </summary>
        internal static string MainForm_SavingProfileDataFailed {
            get {
                return ResourceManager.GetString("MainForm_SavingProfileDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} selected / {1} displayed.
        /// </summary>
        internal static string MainForm_SelectedDisplayed {
            get {
                return ResourceManager.GetString("MainForm_SelectedDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Some of the selected games already have categories set. Would you like to overwrite these categories?.
        /// </summary>
        internal static string MainForm_SomeSelectedGameHaveCategories {
            get {
                return ResourceManager.GetString("MainForm_SomeSelectedGameHaveCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;Uncategorized&gt;.
        /// </summary>
        internal static string MainForm_Uncategorized {
            get {
                return ResourceManager.GetString("MainForm_Uncategorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unignored game {0}..
        /// </summary>
        internal static string MainForm_UnignoredGame {
            get {
                return ResourceManager.GetString("MainForm_UnignoredGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unsaved changes.
        /// </summary>
        internal static string MainForm_UnsavedChanges {
            get {
                return ResourceManager.GetString("MainForm_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unsaved changes will be lost. Save first?.
        /// </summary>
        internal static string MainForm_UnsavedChangesWillBeLost {
            get {
                return ResourceManager.GetString("MainForm_UnsavedChangesWillBeLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updated {0} categories locally..
        /// </summary>
        internal static string MainForm_UpdatedCategories {
            get {
                return ResourceManager.GetString("MainForm_UpdatedCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updated {0} via web..
        /// </summary>
        internal static string MainForm_UpdatedViaWeb {
            get {
                return ResourceManager.GetString("MainForm_UpdatedViaWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Updated {0} / {1} via web and aborted..
        /// </summary>
        internal static string MainForm_UpdatedViaWebAndAborted {
            get {
                return ResourceManager.GetString("MainForm_UpdatedViaWebAndAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XML download failed..
        /// </summary>
        internal static string MainForm_XMLDownloadFailed {
            get {
                return ResourceManager.GetString("MainForm_XMLDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        internal static string MainForm_Yes {
            get {
                return ResourceManager.GetString("MainForm_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error loading profile:.
        /// </summary>
        internal static string Profile_ErrorLoadingProfile {
            get {
                return ResourceManager.GetString("Profile_ErrorLoadingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error saving profile file:.
        /// </summary>
        internal static string Profile_ErrorSavingProfileFile {
            get {
                return ResourceManager.GetString("Profile_ErrorSavingProfileFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to load profile: {0}.
        /// </summary>
        internal static string Profile_FailedToLoadProfile {
            get {
                return ResourceManager.GetString("Profile_FailedToLoadProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to open profile file for writing: {0}.
        /// </summary>
        internal static string Profile_FailedToOpenProfileFile {
            get {
                return ResourceManager.GetString("Profile_FailedToOpenProfileFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading profile from file: {0}.
        /// </summary>
        internal static string Profile_LoadingProfile {
            get {
                return ResourceManager.GetString("Profile_LoadingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile save complete..
        /// </summary>
        internal static string Profile_ProfileSaveComplete {
            get {
                return ResourceManager.GetString("Profile_ProfileSaveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saving profile: {0}.
        /// </summary>
        internal static string Profile_SavingProfile {
            get {
                return ResourceManager.GetString("Profile_SavingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Program closing..
        /// </summary>
        internal static string Program_ProgramClosing {
            get {
                return ResourceManager.GetString("Program_ProgramClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Program initialized. Logging level set to {0}..
        /// </summary>
        internal static string Program_ProgramInitialized {
            get {
                return ResourceManager.GetString("Program_ProgramInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Node is a value, not an array. Cannot get key {0}.
        /// </summary>
        internal static string TextVdfFile_CanNotGetKey {
            get {
                return ResourceManager.GetString("TextVdfFile_CanNotGetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Node is a value, not an array. Cannot set key {0}.
        /// </summary>
        internal static string TextVdfFile_CanNotSetKey {
            get {
                return ResourceManager.GetString("TextVdfFile_CanNotSetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unexpected character &apos;{0}&apos; found when expecting key..
        /// </summary>
        internal static string TextVdfFile_UnexpectedCharacterKey {
            get {
                return ResourceManager.GetString("TextVdfFile_UnexpectedCharacterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unexpected character &apos;{0}&apos; found when expecting value..
        /// </summary>
        internal static string TextVdfFile_UnexpectedCharacterValue {
            get {
                return ResourceManager.GetString("TextVdfFile_UnexpectedCharacterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unexpected end-of-file reached: Unterminated string..
        /// </summary>
        internal static string TextVdfFile_UnexpectedEOF {
            get {
                return ResourceManager.GetString("TextVdfFile_UnexpectedEOF", resourceCulture);
            }
        }
    }
}
