//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Depressurizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Depressurizer.Properties.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\appcache\appinfo.vdf.
        /// </summary>
        internal static string AppInfoPath {
            get {
                return ResourceManager.GetString("AppInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\userdata\{1}\7\remote\sharedconfig.vdf.
        /// </summary>
        internal static string ConfigFilePath {
            get {
                return ResourceManager.GetString("ConfigFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/mvegter/depressurizer.
        /// </summary>
        internal static string DepressurizerHomepage {
            get {
                return ResourceManager.GetString("DepressurizerHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.github.com/repos/mvegter/Depressurizer/releases/latest.
        /// </summary>
        internal static string DepressurizerLatestRelease {
            get {
                return ResourceManager.GetString("DepressurizerLatestRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.howlongtobeatsteam.com/api/games/library/cached/all.
        /// </summary>
        internal static string HowLongToBeat {
            get {
                return ResourceManager.GetString("HowLongToBeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.gnu.org/licenses/gpl-3.0.en.html.
        /// </summary>
        internal static string LicensePage {
            get {
                return ResourceManager.GetString("LicensePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\userdata\{1}\config\localconfig.vdf.
        /// </summary>
        internal static string LocalConfigPath {
            get {
                return ResourceManager.GetString("LocalConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\appcache\packageinfo.vdf.
        /// </summary>
        internal static string PackageInfoPath {
            get {
                return ResourceManager.GetString("PackageInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\userdata\{1}\760\screenshots.vdf.
        /// </summary>
        internal static string ScreenshotsFilePath {
            get {
                return ResourceManager.GetString("ScreenshotsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\userdata\{1}\config\shortcuts.vdf.
        /// </summary>
        internal static string ShortCutsFilePath {
            get {
                return ResourceManager.GetString("ShortCutsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://steamcommunity.com/id/{0}/games?tab=all.
        /// </summary>
        internal static string SteamCustomProfileGameList {
            get {
                return ResourceManager.GetString("SteamCustomProfileGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://steamcommunity.com/id/{0}/games?tab=all&amp;xml=1.
        /// </summary>
        internal static string SteamCustomProfileGameListXML {
            get {
                return ResourceManager.GetString("SteamCustomProfileGameListXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://steamcommunity.com/profiles/{0}/games?tab=all.
        /// </summary>
        internal static string SteamProfileGameList {
            get {
                return ResourceManager.GetString("SteamProfileGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://steamcommunity.com/profiles/{0}/games?tab=all&amp;xml=1.
        /// </summary>
        internal static string SteamProfileGameListXML {
            get {
                return ResourceManager.GetString("SteamProfileGameListXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://steamcommunity.com/id/{0}?xml=1.
        /// </summary>
        internal static string SteamProfileXML {
            get {
                return ResourceManager.GetString("SteamProfileXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://store.steampowered.com/.
        /// </summary>
        internal static string SteamStore {
            get {
                return ResourceManager.GetString("SteamStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://store.steampowered.com/app/{0}/.
        /// </summary>
        internal static string SteamStoreApp {
            get {
                return ResourceManager.GetString("SteamStoreApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://store.steampowered.com/curator/{0}/ajaxgetfilteredrecommendations/render/?query=&amp;start={1}&amp;count=50.
        /// </summary>
        internal static string UrlSteamCuratorRecommendations {
            get {
                return ResourceManager.GetString("UrlSteamCuratorRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://steamcommunity.com/profiles/{0}?xml=1.
        /// </summary>
        internal static string UrlSteamProfile {
            get {
                return ResourceManager.GetString("UrlSteamProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /profile/avatarIcon.
        /// </summary>
        internal static string XmlNodeAvatar {
            get {
                return ResourceManager.GetString("XmlNodeAvatar", resourceCulture);
            }
        }
    }
}
