//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Depressurizer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Depressurizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add ({0}) 的本地化字符串。
        /// </summary>
        internal static string AddButtonWithCount {
            get {
                return ResourceManager.GetString("AddButtonWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All ({0}) 的本地化字符串。
        /// </summary>
        internal static string AllButtonWithCount {
            get {
                return ResourceManager.GetString("AllButtonWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applied data... 的本地化字符串。
        /// </summary>
        internal static string AppliedData {
            get {
                return ResourceManager.GetString("AppliedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applying data... 的本地化字符串。
        /// </summary>
        internal static string ApplyingData {
            get {
                return ResourceManager.GetString("ApplyingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto-Categorize ({0} Apps) 的本地化字符串。
        /// </summary>
        internal static string AutoCategorizeNumApps {
            get {
                return ResourceManager.GetString("AutoCategorizeNumApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception thrown in thread, stopping... 的本地化字符串。
        /// </summary>
        internal static string CancelableDialog_ThreadErrorStopping {
            get {
                return ResourceManager.GetString("CancelableDialog_ThreadErrorStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Categories 的本地化字符串。
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View &amp;Community 的本地化字符串。
        /// </summary>
        internal static string cmdStore_CommunityText {
            get {
                return ResourceManager.GetString("cmdStore_CommunityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View &amp;Store 的本地化字符串。
        /// </summary>
        internal static string cmdStore_StoreText {
            get {
                return ResourceManager.GetString("cmdStore_StoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete filter &apos;{0}&apos;? 的本地化字符串。
        /// </summary>
        internal static string ConfirmDeleteFilter {
            get {
                return ResourceManager.GetString("ConfirmDeleteFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JSON files (*.json)|*.json 的本地化字符串。
        /// </summary>
        internal static string DatabaseSaveFilter {
            get {
                return ResourceManager.GetString("DatabaseSaveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleted filter &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string DeletedFilter {
            get {
                return ResourceManager.GetString("DeletedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter new name: 的本地化字符串。
        /// </summary>
        internal static string EnterNewName {
            get {
                return ResourceManager.GetString("EnterNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not delete filter &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string FailedDeletingFilter {
            get {
                return ResourceManager.GetString("FailedDeletingFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter &apos;{0}&apos; already exists. 的本地化字符串。
        /// </summary>
        internal static string FilterAlreadyExists {
            get {
                return ResourceManager.GetString("FilterAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Included tags ({0}) 的本地化字符串。
        /// </summary>
        internal static string IncludedTagsWithCount {
            get {
                return ResourceManager.GetString("IncludedTagsWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected item is not a Filter! 的本地化字符串。
        /// </summary>
        internal static string ItemIsNotAFilter {
            get {
                return ResourceManager.GetString("ItemIsNotAFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rebuild List ({0}) 的本地化字符串。
        /// </summary>
        internal static string RebuildListButtonWithCount {
            get {
                return ResourceManager.GetString("RebuildListButtonWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove ({0}) 的本地化字符串。
        /// </summary>
        internal static string RemoveButtonWithCount {
            get {
                return ResourceManager.GetString("RemoveButtonWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename 的本地化字符串。
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename filter &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string RenameFilter {
            get {
                return ResourceManager.GetString("RenameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scraping data... 的本地化字符串。
        /// </summary>
        internal static string ScrapeDialog_Title {
            get {
                return ResourceManager.GetString("ScrapeDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scraped {0}/{1} 的本地化字符串。
        /// </summary>
        internal static string ScrapedProgress {
            get {
                return ResourceManager.GetString("ScrapedProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;All&gt; 的本地化字符串。
        /// </summary>
        internal static string SpecialCategoryAll {
            get {
                return ResourceManager.GetString("SpecialCategoryAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Favorite&gt; 的本地化字符串。
        /// </summary>
        internal static string SpecialCategoryFavorite {
            get {
                return ResourceManager.GetString("SpecialCategoryFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Games&gt; 的本地化字符串。
        /// </summary>
        internal static string SpecialCategoryGames {
            get {
                return ResourceManager.GetString("SpecialCategoryGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Hidden&gt; 的本地化字符串。
        /// </summary>
        internal static string SpecialCategoryHidden {
            get {
                return ResourceManager.GetString("SpecialCategoryHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;No Flags&gt; 的本地化字符串。
        /// </summary>
        internal static string SpecialCategoryNoFlags {
            get {
                return ResourceManager.GetString("SpecialCategoryNoFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;No Genres&gt; 的本地化字符串。
        /// </summary>
        internal static string SpecialCategoryNoGenres {
            get {
                return ResourceManager.GetString("SpecialCategoryNoGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;No Tags&gt; 的本地化字符串。
        /// </summary>
        internal static string SpecialCategoryNoTags {
            get {
                return ResourceManager.GetString("SpecialCategoryNoTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Software&gt; 的本地化字符串。
        /// </summary>
        internal static string SpecialCategorySoftware {
            get {
                return ResourceManager.GetString("SpecialCategorySoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Uncategorized&gt; 的本地化字符串。
        /// </summary>
        internal static string SpecialCategoryUncategorized {
            get {
                return ResourceManager.GetString("SpecialCategoryUncategorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Unknown&gt; 的本地化字符串。
        /// </summary>
        internal static string SpecialCategoryUnknown {
            get {
                return ResourceManager.GetString("SpecialCategoryUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;VR&gt; 的本地化字符串。
        /// </summary>
        internal static string SpecialCategoryVR {
            get {
                return ResourceManager.GetString("SpecialCategoryVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time Left 的本地化字符串。
        /// </summary>
        internal static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
